Import the 5.2.0 version

diff --git a/bin/cypher-shell b/bin/cypher-shell
--- a/bin/cypher-shell
+++ b/bin/cypher-shell
@@ -1,96 +1,128 @@
-#!/bin/bash
+#!/usr/bin/env sh
+# ----------------------------------------------------------------------------
+#  Copyright 2001-2006 The Apache Software Foundation.
+#
+#  Licensed under the Apache License, Version 2.0 (the "License");
+#  you may not use this file except in compliance with the License.
+#  You may obtain a copy of the License at
+#
+#       http://www.apache.org/licenses/LICENSE-2.0
+#
+#  Unless required by applicable law or agreed to in writing, software
+#  distributed under the License is distributed on an "AS IS" BASIS,
+#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+#  See the License for the specific language governing permissions and
+#  limitations under the License.
+# ----------------------------------------------------------------------------
+#
+#   Copyright (c) 2001-2006 The Apache Software Foundation.  All rights
+#   reserved.
 
-set -euo pipefail
-[[ "${TRACE:-}" ]] && set -x
 
-check_java() {
-  _find_java_cmd
+# resolve links - $0 may be a softlink
+PRG="$0"
 
-  version_command=("${JAVA_CMD}" "-version")
-  [[ -n "${JAVA_MEMORY_OPTS:-}" ]] && version_command+=("${JAVA_MEMORY_OPTS[@]}")
-
-  JAVA_VERSION=$("${version_command[@]}" 2>&1 | awk -F '"' '/version/ {print $2}')
-  if [[ $JAVA_VERSION = "1."* ]]; then
-    if [[ "${JAVA_VERSION}" < "1.8" ]]; then
-      echo "ERROR! Java version ${JAVA_VERSION} is not supported. "
-      _show_java_help
-      exit 1
-    fi
+while [ -h "$PRG" ]; do
+  ls=`ls -ld "$PRG"`
+  link=`expr "$ls" : '.*-> \(.*\)$'`
+  if expr "$link" : '/.*' > /dev/null; then
+    PRG="$link"
+  else
+    PRG=`dirname "$PRG"`/"$link"
   fi
-}
+done
 
-_find_java_cmd() {
-  [[ "${JAVA_CMD:-}" ]] && return
-  detect_os
-  _find_java_home
+PRGDIR=`dirname "$PRG"`
+BASEDIR=`cd "$PRGDIR/.." >/dev/null; pwd`
 
-  if [[ "${JAVA_HOME:-}" ]] ; then
-    JAVA_CMD="${JAVA_HOME}/bin/java"
-    if [[ ! -f "${JAVA_CMD}" ]]; then
-      echo "ERROR: JAVA_HOME is incorrectly defined as ${JAVA_HOME} (the executable ${JAVA_CMD} does not exist)"
-      exit 1
+# Reset the REPO variable. If you need to influence this use the environment setup file.
+REPO=
+
+
+# OS specific support.  $var _must_ be set to either true or false.
+cygwin=false;
+darwin=false;
+case "`uname`" in
+  CYGWIN*) cygwin=true ;;
+  Darwin*) darwin=true
+           if [ -z "$JAVA_VERSION" ] ; then
+             JAVA_VERSION="CurrentJDK"
+           else
+             echo "Using Java version: $JAVA_VERSION"
+           fi
+		   if [ -z "$JAVA_HOME" ]; then
+		      if [ -x "/usr/libexec/java_home" ]; then
+			      JAVA_HOME=`/usr/libexec/java_home`
+			  else
+			      JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Home
+			  fi
+           fi       
+           ;;
+esac
+
+if [ -z "$JAVA_HOME" ] ; then
+  if [ -r /etc/gentoo-release ] ; then
+    JAVA_HOME=`java-config --jre-home`
+  fi
+fi
+
+# For Cygwin, ensure paths are in UNIX format before anything is touched
+if $cygwin ; then
+  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
+  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
+fi
+
+# If a specific java binary isn't specified search for the standard 'java' binary
+if [ -z "$JAVACMD" ] ; then
+  if [ -n "$JAVA_HOME"  ] ; then
+    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+      # IBM's JDK on AIX uses strange locations for the executables
+      JAVACMD="$JAVA_HOME/jre/sh/java"
+    else
+      JAVACMD="$JAVA_HOME/bin/java"
     fi
   else
-    if [ "${DIST_OS}" != "macosx" ] ; then
-      # Don't use default java on Darwin because it displays a misleading dialog box
-      JAVA_CMD="$(which java || true)"
-    fi
+    JAVACMD=`which java`
   fi
+fi
 
-  if [[ ! "${JAVA_CMD:-}" ]]; then
-    echo "ERROR: Unable to find Java executable."
-    _show_java_help
-    exit 1
-  fi
-}
-
-detect_os() {
-  if uname -s | grep -q Darwin; then
-    DIST_OS="macosx"
-  elif [[ -e /etc/gentoo-release ]]; then
-    DIST_OS="gentoo"
-  else
-    DIST_OS="other"
-  fi
-}
-
-_find_java_home() {
-  [[ "${JAVA_HOME:-}" ]] && return
-
-  case "${DIST_OS}" in
-    "macosx")
-      JAVA_HOME="$(/usr/libexec/java_home -v 1.8+)"
-      ;;
-    "gentoo")
-      JAVA_HOME="$(java-config --jre-home)"
-      ;;
-  esac
-}
-
-_show_java_help() {
-  echo "* Please use Oracle(R) Java(TM) >=8 or OpenJDK(TM) >=8."
-}
-
-build_classpath() {
-  APP_HOME="$(cd "$(dirname "$0")" && pwd)"
-  # First try in sub directory
-  JARPATH="$(find "${APP_HOME}" -name "cypher-shell.jar" )"
-
-  # Then try installation directory (prefix/bin and prefix/share/cypher-shell/lib)
-  if [[ -z "${JARPATH}" ]]; then
-    APP_HOME="${APP_HOME}/../share/cypher-shell"
-    JARPATH="$(find "${APP_HOME}" -name "cypher-shell.jar" )"
-  fi
-}
-
-check_java
-build_classpath
-
-if [ -z "${JARPATH}" ]; then
-  echo "Unable to locate cypher-shell library files" >&2
+if [ ! -x "$JAVACMD" ] ; then
+  echo "Error: JAVA_HOME is not defined correctly." 1>&2
+  echo "  We cannot execute $JAVACMD" 1>&2
   exit 1
 fi
 
-exec "$JAVA_CMD" ${JAVA_OPTS:-} \
-  -jar "$JARPATH" \
+if [ -z "$REPO" ]
+then
+  REPO="$BASEDIR"/lib
+fi
+
+CLASSPATH="$BASEDIR"/etc:"$REPO"/neo4j-java-driver-5.2.0.jar:"$REPO"/reactive-streams-1.0.4.jar:"$REPO"/netty-handler-4.1.84.Final.jar:"$REPO"/netty-common-4.1.84.Final.jar:"$REPO"/netty-resolver-4.1.84.Final.jar:"$REPO"/netty-buffer-4.1.84.Final.jar:"$REPO"/netty-transport-4.1.84.Final.jar:"$REPO"/netty-transport-native-unix-common-4.1.84.Final.jar:"$REPO"/netty-codec-4.1.84.Final.jar:"$REPO"/netty-tcnative-classes-2.0.54.Final.jar:"$REPO"/reactor-core-3.4.24.jar:"$REPO"/cypher-literal-interpreter-5.2.0.jar:"$REPO"/neo4j-values-5.2.0.jar:"$REPO"/neo4j-graphdb-api-5.2.0.jar:"$REPO"/annotations-5.2.0.jar:"$REPO"/eclipse-collections-11.1.0.jar:"$REPO"/eclipse-collections-api-11.1.0.jar:"$REPO"/commons-lang3-3.12.0.jar:"$REPO"/neo4j-common-5.2.0.jar:"$REPO"/lz4-java-1.8.0.jar:"$REPO"/neo4j-resource-5.2.0.jar:"$REPO"/neo4j-collections-5.2.0.jar:"$REPO"/caffeine-3.1.1.jar:"$REPO"/neo4j-exceptions-5.2.0.jar:"$REPO"/neo4j-unsafe-5.2.0.jar:"$REPO"/jna-5.12.1.jar:"$REPO"/cypher-ast-factory-5.2.0.jar:"$REPO"/neo4j-cypher-javacc-parser-5.2.0.jar:"$REPO"/argparse4j-0.9.0.jar:"$REPO"/jline-terminal-3.21.0.jar:"$REPO"/jline-reader-3.21.0.jar:"$REPO"/jline-terminal-jansi-3.21.0.jar:"$REPO"/jansi-2.4.0.jar:"$REPO"/cypher-shell-5.2.0.jar
+
+ENDORSED_DIR=
+if [ -n "$ENDORSED_DIR" ] ; then
+  CLASSPATH=$BASEDIR/$ENDORSED_DIR/*:$CLASSPATH
+fi
+
+if [ -n "$CLASSPATH_PREFIX" ] ; then
+  CLASSPATH=$CLASSPATH_PREFIX:$CLASSPATH
+fi
+
+# For Cygwin, switch paths to Windows format before running java
+if $cygwin; then
+  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
+  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
+  [ -n "$HOME" ] && HOME=`cygpath --path --windows "$HOME"`
+  [ -n "$BASEDIR" ] && BASEDIR=`cygpath --path --windows "$BASEDIR"`
+  [ -n "$REPO" ] && REPO=`cygpath --path --windows "$REPO"`
+fi
+
+exec "$JAVACMD" $JAVA_OPTS  \
+  -classpath "$CLASSPATH" \
+  -Dapp.name="cypher-shell" \
+  -Dapp.pid="$$" \
+  -Dapp.repo="$REPO" \
+  -Dapp.home="$BASEDIR" \
+  -Dbasedir="$BASEDIR" \
+  org.neo4j.shell.startup.CypherShellBoot \
   "$@"
