Import new upstream release

diff --git a/bin/neo4j-admin b/bin/neo4j-admin
--- a/bin/neo4j-admin
+++ b/bin/neo4j-admin
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/sh
 # Copyright (c) "Neo4j"
 # Neo4j Sweden AB [http://neo4j.com]
 #
@@ -16,234 +16,113 @@
 #
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
-
-set -o errexit -o nounset -o pipefail
-[[ "${TRACE:-}" ]] && set -o xtrace
-
-PROGRAM="$(basename "$0")"
-readonly PROGRAM
-
-# Sets up the standard environment for running Neo4j shell scripts.
 #
-# Provides these environment variables:
-#   NEO4J_HOME
-#   NEO4J_CONF
-#   NEO4J_DATA
-#   NEO4J_LIB
-#   NEO4J_LOGS
-#   NEO4J_PIDFILE
-#   NEO4J_PLUGINS
-#   one per config setting, with dots converted to underscores
-#
-setup_environment() {
-  _setup_calculated_paths
-  _read_config
-  _setup_configurable_paths
-}
 
-setup_heap() {
-  if [[ -n "${HEAP_SIZE:-}" ]]; then
-    JAVA_MEMORY_OPTS_XMX="-Xmx${HEAP_SIZE}"
-  fi
-}
 
-build_classpath() {
-  CLASSPATH="${NEO4J_PLUGINS}:${NEO4J_CONF}:${NEO4J_LIB}/*:${NEO4J_PLUGINS}/*"
-}
+# resolve links - $0 may be a softlink
+PRG="$0"
 
-detect_os() {
-  if uname -s | grep -q Darwin; then
-    DIST_OS="macosx"
+while [ -h "$PRG" ]; do
+  ls=`ls -ld "$PRG"`
+  link=`expr "$ls" : '.*-> \(.*\)$'`
+  if expr "$link" : '/.*' > /dev/null; then
+    PRG="$link"
   else
-    DIST_OS="other"
+    PRG=`dirname "$PRG"`/"$link"
   fi
-}
+done
 
-check_limits() {
-  detect_os
-  MIN_ALLOWED_OPEN_FILES=40000
-  if [ "${DIST_OS}" != "macosx" ] ; then
-    ALLOWED_OPEN_FILES="$(ulimit -n)"
+PRGDIR=`dirname "$PRG"`
+BASEDIR=`cd "$PRGDIR/.." >/dev/null; pwd`
 
-    if [ "${ALLOWED_OPEN_FILES}" -lt "${MIN_ALLOWED_OPEN_FILES}" ]; then
-        echo "WARNING: Max ${ALLOWED_OPEN_FILES} open files allowed, minimum of ${MIN_ALLOWED_OPEN_FILES} recommended. See the Neo4j manual."
-    fi
+# Reset the REPO variable. If you need to influence this use the environment setup file.
+REPO=
+
+
+# OS specific support.  $var _must_ be set to either true or false.
+cygwin=false;
+darwin=false;
+case "`uname`" in
+  CYGWIN*) cygwin=true ;;
+  Darwin*) darwin=true
+           if [ -z "$JAVA_VERSION" ] ; then
+             JAVA_VERSION="CurrentJDK"
+           else
+             echo "Using Java version: $JAVA_VERSION"
+           fi
+		   if [ -z "$JAVA_HOME" ]; then
+		      if [ -x "/usr/libexec/java_home" ]; then
+			      JAVA_HOME=`/usr/libexec/java_home`
+			  else
+			      JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Home
+			  fi
+           fi       
+           ;;
+esac
+
+if [ -z "$JAVA_HOME" ] ; then
+  if [ -r /etc/gentoo-release ] ; then
+    JAVA_HOME=`java-config --jre-home`
   fi
-}
+fi
 
-setup_memory_opts() {
-  # In some cases the heap size may have already been set before we get here, from e.g. HEAP_SIZE env.variable, if so then skip
-  if [[ -n "${dbms_memory_heap_max_size:-}" && -z "${JAVA_MEMORY_OPTS_XMX-}" ]]; then
-    if ! [[ "${dbms_memory_heap_max_size}" =~ .*[gGmMkK] ]]; then
-      cat >&2 <<EOF
-ERROR: dbms.memory.heap.max_size require a unit suffix. Use
-       'k' for kilobytes, 'm' for megabytes and 'g' for gigabytes.
-       Example:
+# For Cygwin, ensure paths are in UNIX format before anything is touched
+if $cygwin ; then
+  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
+  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
+fi
 
-       dbms.memory.heap.max_size=512m
-                                    ^
-EOF
-      exit 1
-    fi
-    JAVA_MEMORY_OPTS_XMX="-Xmx${dbms_memory_heap_max_size}"
-  fi
-}
-
-check_java() {
-  _find_java_cmd
-  setup_memory_opts
-
-  version_command=("${JAVA_CMD}" "-version")
-
-  JAVA_VERSION=$("${version_command[@]}" 2>&1 | awk -F '"' '/version/ {print $2}')
-  if [[ $JAVA_VERSION = "1."* ]] || [[ $JAVA_VERSION = "9"* ]] || [[ $JAVA_VERSION = "10"* ]]; then
-      echo "ERROR! Neo4j cannot be started using java version ${JAVA_VERSION}. "
-      _show_java_help
-      exit 1
-  elif [[ $JAVA_VERSION != "11"* ]] ; then
-    unsupported_runtime_warning
-  else
-    if ! ("${version_command[@]}" 2>&1 | grep -Eq "(Java HotSpot\\(TM\\)|OpenJDK) (64-Bit Server|Server|Client) VM"); then
-      unsupported_runtime_warning
-    fi
-  fi
-}
-
-unsupported_runtime_warning() {
-    echo "WARNING! You are using an unsupported Java runtime. "
-    _show_java_help
-}
-
-# Resolve a path relative to $NEO4J_HOME.  Don't resolve if
-# the path is absolute.
-resolve_path() {
-    orig_filename=$1
-    if [[ ${orig_filename} == /* ]]; then
-        filename="${orig_filename}"
+# If a specific java binary isn't specified search for the standard 'java' binary
+if [ -z "$JAVACMD" ] ; then
+  if [ -n "$JAVA_HOME"  ] ; then
+    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+      # IBM's JDK on AIX uses strange locations for the executables
+      JAVACMD="$JAVA_HOME/jre/sh/java"
     else
-        filename="${NEO4J_HOME}/${orig_filename}"
-    fi
-    echo "${filename}"
-}
-
-_find_java_cmd() {
-  [[ "${JAVA_CMD:-}" ]] && return
-  detect_os
-  _find_java_home
-
-  if [[ "${JAVA_HOME:-}" ]] ; then
-    JAVA_CMD="${JAVA_HOME}/bin/java"
-    if [[ ! -f "${JAVA_CMD}" ]]; then
-      echo "ERROR: JAVA_HOME is incorrectly defined as ${JAVA_HOME} (the executable ${JAVA_CMD} does not exist)"
-      exit 1
+      JAVACMD="$JAVA_HOME/bin/java"
     fi
   else
-    if [ "${DIST_OS}" != "macosx" ] ; then
-      # Don't use default java on Darwin because it displays a misleading dialog box
-      JAVA_CMD="$(command -v java || true)"
-    fi
+    JAVACMD=`which java`
   fi
+fi
 
-  if [[ ! "${JAVA_CMD:-}" ]]; then
-    echo "ERROR: Unable to find Java executable. Make sure the java executable is on the PATH or define JAVA_HOME."
-    _show_java_help
-    exit 1
-  fi
-}
+if [ ! -x "$JAVACMD" ] ; then
+  echo "Error: JAVA_HOME is not defined correctly." 1>&2
+  echo "  We cannot execute $JAVACMD" 1>&2
+  exit 1
+fi
 
-_find_java_home() {
-  [[ "${JAVA_HOME:-}" ]] && return
+if [ -z "$REPO" ]
+then
+  REPO="$BASEDIR"/repo
+fi
 
-  case "${DIST_OS}" in
-    "macosx")
-      JAVA_HOME="$(/usr/libexec/java_home -v 11)"
-      ;;
-  esac
-}
+CLASSPATH="$BASEDIR"/etc:"$REPO"/*
 
-_show_java_help() {
-  echo "* Please use Oracle(R) Java(TM) 11, OpenJDK(TM) 11 to run Neo4j."
-  echo "* Please see https://neo4j.com/docs/ for Neo4j installation instructions."
-}
+ENDORSED_DIR=lib
+if [ -n "$ENDORSED_DIR" ] ; then
+  CLASSPATH=$BASEDIR/$ENDORSED_DIR/*:$CLASSPATH
+fi
 
-_setup_calculated_paths() {
-  if [[ -z "${NEO4J_HOME:-}" ]]; then
-    NEO4J_HOME="$(cd "$(dirname "$0")"/.. && pwd)"
-  fi
-  : "${NEO4J_CONF:="${NEO4J_HOME}/conf"}"
-  readonly NEO4J_HOME NEO4J_CONF
-}
+if [ -n "$CLASSPATH_PREFIX" ] ; then
+  CLASSPATH=$CLASSPATH_PREFIX:$CLASSPATH
+fi
 
-_read_config() {
-  # - plain key-value pairs become environment variables
-  # - keys have '.' chars changed to '_'
-  # - keys of the form KEY.# (where # is a number) are concatenated into a single environment variable named KEY
-  parse_line() {
-    line="$1"
-    if [[ "${line}" =~ ^([^#\s][^=]+)=(.+)$ ]]; then
-      key="${BASH_REMATCH[1]//./_}"
-      value="${BASH_REMATCH[2]}"
-      if [[ "${key}" =~ ^(.*)_([0-9]+)$ ]]; then
-        key="${BASH_REMATCH[1]}"
-      fi
-      # Ignore keys that start with a number because export ${key}= will fail - it is not valid for a bash env var to start with a digit
-      if [[ ! "${key}" =~ ^[0-9]+.*$ ]]; then
-        if [[ "${key}" == "dbms_jvm_additional" && "${!key:-}" ]]; then
-          export "${key}=${!key} ${value}"
-        else
-          export "${key}=${value}"
-        fi
-      else
-        echo >&2 "WARNING: Ignoring key ${key}, environment variables cannot start with a number."
-      fi
-    fi
-  }
+# For Cygwin, switch paths to Windows format before running java
+if $cygwin; then
+  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
+  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
+  [ -n "$HOME" ] && HOME=`cygpath --path --windows "$HOME"`
+  [ -n "$BASEDIR" ] && BASEDIR=`cygpath --path --windows "$BASEDIR"`
+  [ -n "$REPO" ] && REPO=`cygpath --path --windows "$REPO"`
+fi
 
-  path="${NEO4J_CONF}/neo4j.conf"
-  if [ -e "${path}" ]; then
-
-    # we want to get multi lines as a single value
-    # shellcheck disable=SC2162
-    while read line || [[ -n "$line" ]]; do
-      parse_line "${line}"
-    done <"${path}"
-  fi
-}
-
-_setup_configurable_paths() {
-  NEO4J_DATA=$(resolve_path "${dbms_directories_data:-data}")
-  NEO4J_LIB=$(resolve_path "${dbms_directories_lib:-lib}")
-  NEO4J_LOGS=$(resolve_path "${dbms_directories_logs:-logs}")
-  NEO4J_PLUGINS=$(resolve_path "${dbms_directories_plugins:-plugins}")
-  NEO4J_RUN=$(resolve_path "${dbms_directories_run:-run}")
-  NEO4J_CERTS=$(resolve_path "${dbms_directories_certificates:-certificates}")
-
-  if [ -z "${dbms_directories_import:-}" ]; then
-    NEO4J_IMPORT="NOT SET"
-  else
-    NEO4J_IMPORT=$(resolve_path "${dbms_directories_import:-}")
-  fi
-
-  readonly NEO4J_DATA NEO4J_LIB NEO4J_LOGS NEO4J_PLUGINS NEO4J_RUN NEO4J_IMPORT NEO4J_CERTS
-}
-
-
-call_main_class() {
-  setup_environment
-  check_limits
-  check_java
-  build_classpath
-  class_name=$1
-  shift
-
-  export NEO4J_HOME NEO4J_CONF
-
-  # shellcheck disable=SC2086
-  exec "${JAVA_CMD}" ${JAVA_OPTS:--XX:+UseParallelGC} ${JAVA_MEMORY_OPTS_XMX-} \
-    -classpath "${CLASSPATH}" \
-    "-Dfile.encoding=UTF-8" \
-    "$class_name" "$@"
-}
-
-setup_heap
-call_main_class "org.neo4j.cli.AdminTool" "$@"
+exec "$JAVACMD" $JAVA_OPTS -Xmx128m \
+  -classpath "$CLASSPATH" \
+  -Dapp.name="neo4j-admin" \
+  -Dapp.pid="$$" \
+  -Dapp.repo="$REPO" \
+  -Dapp.home="$BASEDIR" \
+  -Dbasedir="$BASEDIR" \
+  org.neo4j.server.startup.Neo4jAdminCommand \
+  "$@"
